### ISSUE TITLE
Update README to state why you it is safe to have the gem installed on the web environment

### ISSUE THREAD

**Issue by zaaroth** [tawan/active-elastic-job#11]
The worker is safe by default because the rails application will listen only on localhost and thus only the daemon is able to communicate. So any message the rails application receives is bound to be sent by the daemon.

On the other hand, the web application is exposed and anyone could curl a request with the right user agent and stuff. I assume the message digest is meant to keep "odd" requests at bay and prevent people from spoofing the web environment into processing jobs. I had to dig a bit into the code to ensure this was covered, so it is useful to point out.

**Comment by tawan** [comment]
Thanks for your comment. I will update the README to point this out more clearly.

**Comment by tawan** [comment]
I was also thinking of introducing a boolean environment variable that one has to set when creating the worker environment. This variable will be checked for presence and truthyness before proceeding to execute the job. May I ask you for your opinion on this?

**Comment by zaaroth** [comment]
Thanks for asking. That would be good, but I really like the idea of being transparent to the user, so perhaps another idea would be to figure out when you are attached to something other than localhost (since workers are only attached to localhost) and disable the middleware if that's the case. This would keep things simple to the user, but hard on the gem dev :-) The best way would be to only enable the middleware when running on a worker.

**Comment by zaaroth** [comment]
Thinking it through, if the middleware is disabled on the web environment there is likely no need to validate the messages. I assume in this case they are bound to always come form the attached queue (i.e. from the daemon).

**Comment by zaaroth** [comment]
Perhaps checking the remote_ip of the request would do the trick. If it is not localhost/127.0.0.1 it is safe to ignore the request since the daemon only sends requests locally. This way any attacker would have to hack into the server to spoof anything. If that happens the owner the the environment already has a bigger problem to deal with :-)

**Comment by tawan** [comment]
Thanks for your input.

I think I will add the check of the remote_ip as you suggested.

Furthermore I think I'll introduce an additional environment variable for the web env which disables the middleware. Since there is already a section that explains which environment variables have to be set in the web env, than this should not put too much burden on the user.

I will leave the message signing still in place, just to keep this attack vector closed. Maybe I will make this optional later on.

Great to have an additional pair of eyes having a look. I appreciate your input @zaaroth .

**Comment by zaaroth** [comment]
Nice. I did some extensive research and I find big value in this gem. resque, sidekiq and stuff are really cool, but nowadays the best thing is not having to worry with operations. Deploying any of those things in production means updating software, installing some kind of monitoring and having to keep tabs on lots of stuff (including scaling). I dont have time for that, so having my whole code in one place and deploying with a click on a scaling and monitored environment has BIG value. This gem is gonna be a life saver once it gets stable.

**Comment by tawan** [comment]
:+1:  Agree.

The advantage of Elastic Beanstalk and other PaaS is that you do not need to worry about the infrastructure so much and you can deploy your app with one command and EB takes care of the rest. And it makes sense to keep it that simple.

Given that your application is deployed on EB, than there are two reasons to use worker environments, rather than running your own queueing backend solution.

1. **SQS**: If you run your own queue and background job solution (Resque or Sidekiq, etc.), either as a process within a web environment or in an external EC2 instance, than you are also responsible for keeping this service healthy (protect against data loss, monitoring, etc.). SQS does all this for you.

1. **Uniformity**: You should keep the nodes of your _distributed system_ as similar as possible to reduce complexity. Worker environments provide you the same stack that you already use for your web applications in web environments. The SQS daemon transforms messages into HTTP requests, therefore you only have to deal with one protocol. You can deploy your application to both environments, web and worker, and keep everything in one codebase. Deployment stays at simple as it was, and this simplicity is one of the reasons to use EB in the first place.

I think I will add our reasoning to the README as well.

**Comment by zaaroth** [comment]
Yep. I think the unique downsize I see so far is that a worker environment does not allow you to assign more than one queue to the same pool. It does not matter much to me at this point, but if you are working on small stuff that might set you back a few bucks. That's a given with the other options (resque, sidekiq and stuff).

**Comment by tawan** [comment]
Yep that's true. Each queue will require at least one micro instance, which adds to the bill. So in the end it's an economical question. Is the gained comfort worth the money.

**Comment by zaaroth** [comment]
It is a bit more than that. The real question is whether you gotta be up and running 24/7 (i.e. your business is for real). If your business depends on being up and running it is indeed worth the money. My team is highly optimized (to not say small). It is expensive to waste 1/4 to 1/3 of a developer to keep tabs on whether jobs are being processed or the delay in delivery is small enough. Especally when there is actuallly a pretty "cheap" (when compared to the alternatives) solution available - Amazon's + yours.
