### ISSUE TITLE
Great library

### ISSUE THREAD

**Issue by karensg** [tawan/active-elastic-job#19]
Hi @tawan,

Thanks for sharing this great library and clear instructions. I just installed it and everything worked fine from the first time.

-  I am considering to use it in production and I am wondering what can go wrong? I assume that once installed, it keeps working, right? Is this library vulnerable to sudden AWS changes? Are there any other risks?
- Is there a way that I can keep track of succesful jobs?

Karens

**Comment by tawan** [comment]
Hi @karensg,
Thanks for your feedback.

If you use this gem in production, then I would recommend that you get familiar with Amazon SQS itself. The [developer's guide](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/Welcome.html) provides a good overview. It's good to know how SQS handles message visibility, what is actually meant by that, how the messages are ordered, and if the queue is fault tolerant (which it is).

>  Is this library vulnerable to sudden AWS changes?

I don't think that there is a great risk, because the interface on which this gem relies on is quite simple. For sending messages it uses the [official client](https://github.com/aws/aws-sdk-ruby) of Amazon, and for receiving the messages it processes normal HTTP/1.1requests.

> Are there any other risks?

* The queue is managed by AWS, so you should not have to worry about messages arriving at their destination (your worker tier). Once the message arrives, it will execute the job. If the job execution raises an error, the message will go back to the queue, and probably be fetched again after a while. If the job fails several times, the message will land in a dead letter queue, which you can examine manually. I don't think there is a risk in losing jobs.

* You have to protect your web environment. This is important. Do not forget to set the `DISABLE_SQS_CONSUMER` environment to `true` in the web environment. The gem additionally takes care of signing the messages. Your worker is not accessible from the internet. AWS takes care of this.

> Is there a way that I can keep track of successful jobs?

You can examine the SQS queue from your AWS console. There you will see which messages are queued and how many messages are in flight (meaning job is processed currently). And you can also inspect the dead letter queue, where messages of failed jobs are parked. Other than that, you can simple log some information.

```Ruby
class YourJob < ActiveJob::Base
  def preform(*args)
    # does something
    Rails.logger.info "The job was successful"
  end
end
```
You have to set the [logger level](http://guides.rubyonrails.org/debugging_rails_applications.html#the-logger) accordingly if you use this approach.

Hope this answers your questions.

Cheers,

tawan

**Comment by karensg** [comment]
Thanks for the reading advice, I have gone through the documentation today and it is became more clear. I have configured the main and the dead letter queue and I think I am ready to go. Emails and errors logged and cronjobs configured.

I am glad I found your repo, I will keep track of it for a while.

Keep up the good work!
