### ISSUE TITLE
Local development environment

### ISSUE THREAD

**Issue by Onumis** [tawan/active-elastic-job#22]
I was wondering how would the local development be like with this gem?

Jobs should still be queued on SQS, but I can't see how those jobs would be retrieved and ran locally.
Any idea on how this is done?
I'd think this gem could provide a simple command/rake task that periodically fetches messages form the specified queues. 

(I'm trying to replace Shoryuken with this gem in an effort to move our production environment to AWS EB.)

**Comment by zaaroth** [comment]
You got a couple options. You may do nothing and let active job run inline (right after the job creation in the same thread) or setup resque or some other broker and configure active job to use that.

**Comment by Onumis** [comment]
Yeah, I do enjoy the simplicity of letting the jobs run inline, think I'll go with that approach for now.
Thanks @zaaroth.

**Comment by zaaroth** [comment]
It is usually safe to do so, just be careful with the size of the parameters passed to active job. There is a max size in place with regards to SQS.

**Comment by zaaroth** [comment]
@tawan Pehaps it is a good idea to clarify howto/limitations of dev environment on the README?

**Comment by Onumis** [comment]
Yeah, I was thinking about this and albeit it is indeed simple to have something like:

```
class Application < Rails::Application
  #...  
  if Rails.env.production?
    config.active_job.queue_adapter = :active_elastic_job
  end
end
```

It is bad when you're developing towards a micro-services powered application.
In that case you really want to have messages going around and letting your services interact in the expected way.

**Comment by tawan** [comment]
@Onumis Rails provides configuration files in `config/environments`. So instead of the the `if` condition you can set the active job adapter in these files:
 ```ruby
# config/environments/development.rb
Rails.application.configure do
#...
  config.active_job.queue_adapter = :inline
end
 ```
and for production
```ruby
# config/environments/production.rb
Rails.application.configure do
#...
  config.active_job.queue_adapter = :active_elastic_job
end
```

With this configuration, the background jobs will be immediately executed while developing, which has it advantages. However, it is true that you should test the whole round trip before you deploy to production. I suggest that you create a staging environment in EB (web + worker) next to your production environment where you test the application before you deploy.

@zaaroth Good idea. I will update the README.
