### ISSUE TITLE
Schedule jobs for more than 15 minutes in the future

### ISSUE THREAD

**Issue by ACPK** [tawan/active-elastic-job#45]
When using this gem, what is the recommended way to supplement it in order to execute jobs in the future (ex: emails)?

**Comment by tawan** [comment]
Hi @ACPK 

If you want to execute jobs at a specific point in the future, I'd recommend to have a look at Elastic Beanstalk's Periodic Tasks (Cronjob for Elastic Beanstalk). There is already a discussion ongoing, wether this gem will support periodic tasks in the future. See issue #40 .

Cheers,

Tawan

**Comment by ACPK** [comment]
@tawan - This is more for drip emails.

**Comment by ACPK** [comment]
@tawan - Thoughts?

**Comment by tawan** [comment]
@ACPK Hi,

For this use case, I still think that a periodic cron job is the right approach. This gem supports periodic tasks since 2.0.0 (have a look at the README on how to configure a such task).

Let me sketch it out:

First you need a job that will be executed every 5 minutes (depends on how accurate you need it to be). Lets call it `PrepareShoppingCartMailsJob`.

```Ruby
  class PrepareShoppingCartMailsJob < ActiveJob::Base
    # change to the actual name of your queue
    queue_as :name_of_your_queue

    def perform() # takes no arguments
      # find all shopping carts that have been left more than 1 hour ago
      # and for which the owner has not received a reminder mail, yet.
      shopping_carts = ShoppingCart.where("left_at < ?", 1.hour.ago).where(:sent_mail, false)
      shoppping_carts.each do |s|
        # Create a job for each of the found shopping carts that will actually send the mail
        SendReminderMailJob.perform_later(s)
      end
    end   
  end
  ```

Then add a `cron.yaml` file to the root of your project with this content:

 ```Yaml

  version: 1
  cron:
   - name: "PrepareShoppingCartMailsJob"
     url: "/periodic_tasks"
     schedule: "*/5 * * * *"
  ```

This setup will send a mail approximately 1 hour +/- 5 minutes +/- some delay imposed by a congestion in your queue.

Hope that helps,

tawan

**Comment by ACPK** [comment]
Tawan,

You're amazing!
