### ISSUE TITLE
How is multiple jobs processed ?

### ISSUE THREAD

**Issue by lovesmall** [tawan/active-elastic-job#47]
Hi,

If there is 10 jobs coming (assume each job requires 50% CPU running for 2 min), how many will the worker server takes and processes ?

As I used Resque before, I can set worker number to 2 per server, so the server will take only 2 jobs at one time and using 10 mins to finish all the job. And I can view the process detail via a web UI.

So I want to know if I could set a worker number for the AEJ like resque? And also can I view the current processing jobs like Resque web UI?

Thanks, the AEJ is a great tool to enjoy aws eb with no extra pain = ]

**Comment by lovesmall** [comment]
Emm... based my test, if I flood the server with background jobs, the worker server will just try to process as much as possible. And result few jobs timeout due to, most likely, too many jobs fighting for resources.

So not sure if it's possible to process job in a orderly fashion?  Really appreciate if @tawan could give a bit guide.

**Comment by tawan** [comment]
Hi @lovesmall 

Thanks for you submission!

One major advantage of Elastic Beanstalk Worker environments is the [autoscaling feature](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-types.html?icmpid=docs_elasticbeanstalk_console). If enabled, it launches additional EC2 instances when load increases. Given your example, autoscaling would start additional woker servers, because the original server's load increased. You can enable the autoscaling feature when you launch the worker environment. See the screenshot below!

<img width="712" alt="screen shot 2016-09-26 at 20 54 25" src="https://cloud.githubusercontent.com/assets/6555/18847936/6db595ea-842c-11e6-8dfd-6a700dcff5a6.png">

Given your example, I'd also reduce the number of concurrent requests to **2**. This will prevent a worker instance from fetching 10 jobs at once. As you have mentioned, a job requires 50% CPU time, it makes sense, to limit a server to two concurrent jobs, which you can achieve by reducing the number of concurrent HTTP connections. 
<img width="1045" alt="screen shot 2016-09-26 at 20 55 41" src="https://cloud.githubusercontent.com/assets/6555/18848036/cb641568-842c-11e6-9bd7-f87a43e3ca79.png">
 

Hope the answers your question!

If so, feel free to update the FAQ section of the README, and issuing a pull request. Only if you want of course ;)

Cheers,

Tawan

**Comment by lovesmall** [comment]
Hi Tawan,

Thank you SO MUCH for tell me the HTTP connections setting, just when I was about to switch back to resque. It works good now.

I'm using auto-scaling but this issue is not related to that. Because even with auto-scaling, i still need handle jobs in an orderly way, as I could have large number of jobs comes in few seconds, and I need "NOT" allow worker takes in too many jobs simultaneously.

For the HTTP connection, I've set my worker server to 2. When there are 200+ message in the queue, I could see  3 or 4 messages "In Flight" at any time now(which is fine). Shouldn't it be "2" at most? Is it like this:

1. Send a message to worker via HTTP request, a HTTP connection is established. 
2. The HTTP connection is kept open while worker process the job.
3. Worker finish job and delete the message, HTTP connection is closed.

Thank you if you could clarify a bit on this.


Best,
Yiheng

**Comment by tawan** [comment]
Hi @lovesmall 

Basically you have correctly described the message's lifecycle when consumed by EB worker environments.

1. Message is in queue (visible)
2. EB worker SQS daemon fetches message from queue (in flight)
3. SQS Daemon tries to establish an HTTP connection to the worker application but blocks as long as max other HTTP connections are already open. When the max HTTP connection setting is set to 2, this means that in total 3 messages can be in flight at this step. The third message in flight, is the one that the daemon already fetched from the queue, but it has to wait until it can open an HTTP connection.
3. The HTTP is established and the message is passed as an HTTP request to the worker application.
4. The worker application responds with an 200 OK status
5. The SQS daemon sends a DELETE message call to the queue.

Please, also have a look at this [SO discussion](http://stackoverflow.com/questions/19792881/why-do-sqs-messages-sometimes-remain-in-flight-on-queue).

Cheers,

Tawan

**Comment by rccassity** [comment]
> Hi @lovesmall
> 
> Thanks for you submission!
> 
> One major advantage of Elastic Beanstalk Worker environments is the [autoscaling feature](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-types.html?icmpid=docs_elasticbeanstalk_console). If enabled, it launches additional EC2 instances when load increases. Given your example, autoscaling would start additional woker servers, because the original server's load increased. You can enable the autoscaling feature when you launch the worker environment. See the screenshot below!
> 
> <img alt="screen shot 2016-09-26 at 20 54 25" width="712" src="https://cloud.githubusercontent.com/assets/6555/18847936/6db595ea-842c-11e6-8dfd-6a700dcff5a6.png">
> 
> Given your example, I'd also reduce the number of concurrent requests to **2**. This will prevent a worker instance from fetching 10 jobs at once. As you have mentioned, a job requires 50% CPU time, it makes sense, to limit a server to two concurrent jobs, which you can achieve by reducing the number of concurrent HTTP connections.
> <img alt="screen shot 2016-09-26 at 20 55 41" width="1045" src="https://cloud.githubusercontent.com/assets/6555/18848036/cb641568-842c-11e6-9bd7-f87a43e3ca79.png">
> 
> Hope the answers your question!
> 
> If so, feel free to update the FAQ section of the README, and issuing a pull request. Only if you want of course ;)
> 
> Cheers,
> 
> Tawan
@tawan 
I saw your comment from four years ago. When enabling autoscaling on a worker environment, a load balancer will have to be created manually, correct? My autoscaling worker environment is stuck in a Severe Health State. I have tried relaunching the environment but I still cannot sustain a healthy environment. Environment health has transitioned from No Data to Severe. Do you have any additional instructions? Thank you!
