### ISSUE TITLE
No route matches [POST] "/periodic_tasks

### ISSUE THREAD

**Issue by ACPK** [tawan/active-elastic-job#55]
I get the following error for the cron.yml:

No route matches [POST] "/periodic_tasks

**Comment by tawan** [comment]
Hi @ACPK ,

Thanks for your submission. Sorry for the late response.

Did you set the environment variable **PROCESS_ACTIVE_ELASTIC_JOBS** to `true` ?
Since version 2.0 processing of jobs is disabled per default and has to be enabled via this environment variable as described in the [README](https://github.com/tawan/active-elastic-job/blob/master/README.md) in step 6.

Alternatively, if you have set up a separate Rails environment for your worker environments, then you can also enable the processing of jobs via the Rails configuration:

 ```Ruby
  # config/environments/worker.rb
  Rails.application.configure do
    config.active_elastic_job.process_jobs = true
  end
```

Let me know if this was or wasn't the issue.

Thanks!

Cheers,

Tawan

**Comment by garrinmf** [comment]
@ACPK I was having this exact same problem and after lots of double checking and debugging I found that I'd installed the gem @ version 1.7 and never updated to the latest 2.0.  Upgrading to 2.0.0 and deploying fixed this for me.

**Comment by ACPK** [comment]
@tawan - I have tried both with no luck.

@tawan  - I'm using 2.0.1.

**Comment by ACPK** [comment]
@tawan - I still get a 404 for posts to /periodic_tasks.

**Comment by AdilSarwarNU** [comment]
@ACPK did you resolve this?

**Comment by ACPK** [comment]
@AdilSarwarNU  - I don't believe it was resolved though I am no longer using active-elastic-job. It seems like I wasn't the only person hitting the error so I don't know if was resolved.
